
Logging to /home/yuezk/yzk/ViTac/ManiSkill-ViTac2024/scripts/../training_log/long_open_lock_2024-03-11_20-41-54.395/SAC_1
/home/yuezk/anaconda3/envs/mani_vitac/lib/python3.10/site-packages/stable_baselines3/common/callbacks.py:403: UserWarning: Training and eval env are not of the same type<stable_baselines3.common.vec_env.subproc_vec_env.SubprocVecEnv object at 0x7f49e2579db0> != <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7f48b017dd80>
  warnings.warn("Training and eval env are not of the same type" f"{self.training_env} != {self.eval_env}")
Traceback (most recent call last):
  File "/home/yuezk/yzk/ViTac/ManiSkill-ViTac2024/scripts/train_sac.py", line 178, in <module>
    model.learn(
  File "/home/yuezk/yzk/ViTac/ManiSkill-ViTac2024/scripts/../solutions/sac_custom.py", line 307, in learn
    return super().learn(
  File "/home/yuezk/anaconda3/envs/mani_vitac/lib/python3.10/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 312, in learn
    rollout = self.collect_rollouts(
  File "/home/yuezk/anaconda3/envs/mani_vitac/lib/python3.10/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 541, in collect_rollouts
    actions, buffer_actions = self._sample_action(learning_starts, action_noise, env.num_envs)
  File "/home/yuezk/anaconda3/envs/mani_vitac/lib/python3.10/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 373, in _sample_action
    unscaled_action, _ = self.predict(self._last_obs, deterministic=False)
  File "/home/yuezk/anaconda3/envs/mani_vitac/lib/python3.10/site-packages/stable_baselines3/common/base_class.py", line 555, in predict
    return self.policy.predict(observation, state, episode_start, deterministic)
  File "/home/yuezk/anaconda3/envs/mani_vitac/lib/python3.10/site-packages/stable_baselines3/common/policies.py", line 349, in predict
    actions = self._predict(observation, deterministic=deterministic)
  File "/home/yuezk/yzk/ViTac/ManiSkill-ViTac2024/scripts/../solutions/sb3_sac_policies.py", line 353, in _predict
    return self.actor(observation, deterministic)
  File "/home/yuezk/anaconda3/envs/mani_vitac/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yuezk/yzk/ViTac/ManiSkill-ViTac2024/scripts/../solutions/sb3_sac_policies.py", line 168, in forward
    mean_actions, log_std, kwargs = self.get_action_dist_params(obs)
  File "/home/yuezk/yzk/ViTac/ManiSkill-ViTac2024/scripts/../solutions/sb3_sac_policies.py", line 156, in get_action_dist_params
    latent_pi = self.latent_pi(features)
  File "/home/yuezk/anaconda3/envs/mani_vitac/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yuezk/anaconda3/envs/mani_vitac/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/yuezk/anaconda3/envs/mani_vitac/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yuezk/anaconda3/envs/mani_vitac/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x67 and 64x256)